apiVersion: v1
kind: Namespace
metadata:
  name: agentic-ai-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: agentic-ai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: semitechnologies/weaviate:latest
        ports:
        - containerPort: 8080
        env:
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "true"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: DEFAULT_VECTORIZER_MODULE
          value: "none"
        - name: ENABLE_MODULES
          value: "none"
        volumeMounts:
        - name: weaviate-data
          mountPath: /var/lib/weaviate
      volumes:
      - name: weaviate-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-service
  namespace: agentic-ai-demo
spec:
  selector:
    app: weaviate
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-api
  namespace: agentic-ai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-api
  template:
    metadata:
      labels:
        app: support-api
    spec:
      containers:
      - name: support-api
        image: your-registry/support-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: WEAVIATE_URL
          value: "http://weaviate-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: support-api-service
  namespace: agentic-ai-demo
spec:
  selector:
    app: support-api
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-support-app
  namespace: agentic-ai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-support-app
  template:
    metadata:
      labels:
        app: ai-support-app
    spec:
      containers:
      - name: ai-support-app
        image: your-registry/ai-support-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: LITELLM_CONFIG_PATH
          value: "/app/litellm.config.json"
        - name: API_BASE_URL
          value: "http://support-api-service:8000"
        - name: WEAVIATE_URL
          value: "http://weaviate-service:8080"
        - name: LLAMASTACK_ENDPOINT
          value: "http://llamastack-service:8080"  # Adjust based on your Llamastack setup
---
apiVersion: v1
kind: Service
metadata:
  name: ai-support-app-service
  namespace: agentic-ai-demo
spec:
  selector:
    app: ai-support-app
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-support-route
  namespace: agentic-ai-demo
spec:
  to:
    kind: Service
    name: ai-support-app-service
  port:
    targetPort: 8501