version: '3.8'
services:
  milvus-lite:
    image: milvusdb/milvus:v2.4.10 # Changed from milvus-lite to milvus
    container_name: milvus-lite
    restart: always
    ports:
      - "19530:19530" # Milvus client port
      - "9091:9091"   # Milvus HTTP port (for some tools, not directly used by us)
    volumes:
      - ./milvus_data:/milvus_data # Persist data to a local folder (will be ignored by .gitignore)
    environment:
      # Configuration for Milvus Lite
      - MILVUS_LOG_LEVEL=info
      - MILVUS_PERSISTENCE_ENABLED=true
      - MILVUS_DATA_PATH=/milvus_data
    # IMPORTANT: These settings make it run in standalone/lite mode
      - MILVUS_MODE=standalone
      - ETCD_USE_EMBEDDED=true
      - COMMON_NAME=standalone
      - ALLOW_ANONYMOUS_ACCESS=true # For easier demo access
    command: ["milvus", "run", "standalone"] # This command starts Milvus in standalone mode
    # Remove the healthcheck section entirely if you haven't already,
    # as it can interfere with initial startup for demos.